export const API_URL = 'http://localhost:8000';

export const CATEGORY_PEOPLE = 1;
export const CATEGORY_MUSIC = 2;
export const CATEGORY_STYLE = 3;
export const CATEGORY_GAMING = 4;
export const CATEGORY_ENTERTAINMENT = 5;

export const CATEGORIES = [CATEGORY_ENTERTAINMENT, CATEGORY_PEOPLE, CATEGORY_MUSIC, CATEGORY_STYLE, CATEGORY_GAMING];

export const CATEGORY_TYPE_STRINGS = {
  [CATEGORY_ENTERTAINMENT]: '엔터테인먼트',
  [CATEGORY_PEOPLE]: '사람/일상',
  [CATEGORY_MUSIC]: '음악',
  [CATEGORY_STYLE]: '스타일/패션',
  [CATEGORY_GAMING]: '게임'
};

export const AFFILIATION_INDIVIDUAL = 101;
export const AFFILIATION_MCN = 102;
export const AFFILIATION_GROUP = 103;

export const AFFILIATIONS = [AFFILIATION_INDIVIDUAL, AFFILIATION_MCN, AFFILIATION_GROUP];

export const AFFILIATION_TYPE_STRINGS = {
  [AFFILIATION_INDIVIDUAL]: '개인',
  [AFFILIATION_MCN]: 'MCN',
  [AFFILIATION_GROUP]: '그룹'
};
